### ISSUE TITLE
Breakpoint utility

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/tailwind-config#17]
Add a breakpoint plugin to expose breakpoints in pseudo-elements in order to be able to use theme in JS.

For example:

```scss
[data-breakpoint] {
  &::before {
    content: 's';
    display: none;

    @screen m {
      content: 'm';
    }

    @screen l {
      content: 'l';
    }
  }

  &::after {
    content: '{ "s": 0, "m": 768,  "l": 1280 }';
    display: none;
  }
}
```
