### ISSUE TITLE
The grid plugin does not work with the JIT mode

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/tailwind-config#54]

**Comment by perruche** [comment]
The Studio Meta [grid plugin](https://github.com/studiometa/tailwind-config/blob/develop/src/plugins/grid.js) does not work with the JIT mode.

### How to reproduce 
Active the mode jit
Add a class from the grid plugin with a breakpoint modifier to a tracked template.
The compiled stylesheet will contain some non valid css : 

```css
@media screen (...) {
  @reponsive {
    grid-col-12 {
      width: 100%;
    }
  }
}
```

### Ressources
[JIT documentation page](https://tailwindcss.com/docs/just-in-time-mode)
